spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/trade_platform
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    port: ${DB_PORT}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    format_sql: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
